### ISSUE TITLE
Some early tracks sync'd early

### ISSUE THREAD

**Issue by Dorryza** [OfficiallySp/tftmixer#15]
Thanks for your great work!  I noticed something odd with some of the early tracks.  

If I'm not mistaken, 3 of them (Pentakill, Disco, and probably Country) are sync'd together 8 beats early, probably due to longer lead-in times in their tracks.  The rest of the early tracks seem to be sync'd together correct.  This is particularly noticeable with Jazz - Jazz with an offset fits Disco perfectly, while unmodified Jazz fits most other tracks;  however, there are some tracks that I just don't listen to much, so I may have missed 1 or 2.

I've attached 2 audio files - 1 with Jazz offset by 8 beats and 1 with Jazz not offset at all.  It's my opinion that the offset version makes a lot more sense - it's particularly obvious around 2:20.   The offset that I found worked is about 6.855 seconds.

Keep up the great work!

[Early Jazz+Disco.zip](https://github.com/OfficiallySp/tftmixer/files/14106655/Early.Jazz%2BDisco.zip)

**Comment by OfficiallySp** [comment]
fixed in referenced pr
