### ISSUE TITLE
Found Tracks

### ISSUE THREAD

**Issue by LMMAndreasson** [OfficiallySp/tftmixer#2]
Looked through and found some tracks. There's a lot of different versions of everything, and it's kinda unclear how it's meant to fit together, since certain songs seem to fit in at different parts. There's a lot of layers to the music. Might need some way to classify that. Anyways, here's some tracks I feel fairly certain on.

5 Disco
18 8-bit
34 Maestro (violin, high tempo)
36 Hyperpop (piano)
50 Jazz (Sax)
52 Hyperpop (Vocals)
54 Jazz (More Sax)
55 Jazz (Sax again)
58 Maestro (violin)
59 Country (Bass)
60 KDA (Intro? Outro?)
61 8-bit drums
62 Pentakill? (drums)
63 Punk (guitar)
72 Pentakill

**Comment by OfficiallySp** [comment]
thanks for the label help. much appreciated
