### ISSUE TITLE
Real Time

### ISSUE THREAD

**Issue by alagane** [OfficiallySp/tftmixer#4]
Make the tftmixer real time, if you check a box, the song is added or removed, but it continues playing (like in the game)
Eventually there could be a "timeline" showing where we are in the song, and we would be able to modify it.

Anyway, great work, I thank you for that.

**Comment by OfficiallySp** [comment]
thanks for the kind words. this seems complex to do. i can definately take a shot at it. but i'm very busy with irl stuff this week

**Comment by alagane** [comment]
I tried, synchronizing, waiting all songs to be ready to play with load(), and playing them when they are all ready, only setting the volume to 0 or the globalVolume when toggled with the checkboxes. The songs do not have the same length. Late and early should be grouped together, and for the carousel, I still don't know how it works.

**Comment by alagane** [comment]
I tried, synchronizing, waiting all songs to be ready to play with load(), and playing them when they are all ready, only setting the volume to 0 or the globalVolume when toggled with the checkboxes. The songs do not have the same length. Late and early should be grouped together, and for the carousel, I still don't know how it works.

**Comment by OfficiallySp** [comment]
Added in this PR #11
