### ISSUE TITLE
Country timing off by about 100 ms

### ISSUE THREAD

**Issue by JayWoo2000** [OfficiallySp/tftmixer#6]
I've downloaded your audio files to play with them myself. I've noticed that the country track doesn't align perfectly and I have to slide it to the right a hundred milliseconds. It's also not perfectly aligned on the website as well. Should be a pretty easy fix, I can email the fixed file to you if needed.

**Comment by OfficiallySp** [comment]
hey. if you can send me the file i can replace it. my email is shane.pepperell@me.com
