### ISSUE TITLE
Shared link omits the last track in the selectedTracks parameter

### ISSUE THREAD

**Issue by MaikelVdV** [OfficiallySp/tftmixer#8]
Hi, first of all I want to say that I love the tool that you made! 
When sharing a URL through chat the last track in the mix is omitted because the final seperators you use in the given URL (.,) are not recognized as part of the URL. This can be fixed by running your list of parameters through a URL encoder so that the special characters are encoded to a format that gets properly recognized as part of the URL.

Below is one part self promotion and one part example of how the URL should look when properly encoded:

https://officiallysp.net/tftmixer/?selectedTracks=punk_late_drums%2E%2Cpunk_late_main%2E%2C8bit_late_drums%2E%2Chyperpop_late%2E%2C

**Comment by OfficiallySp** [comment]
Hey hey. So the reason this was done this was a was. A quick and dirty fix for sharing to Reddit. As the extra dot at the end Wouldn't be picked up at the end. This can definitely be done at some point.

**Comment by OfficiallySp** [comment]
Sorry this took so long to implement. This should be now live with the formatting you suggested while also trying to not break legacy urls encoded with a dot or comma
