### ISSUE TITLE
Both Maestro tracks are too loud, early Maestro plays ~2sec too late.

### ISSUE THREAD

**Issue by TheFreeWind** [OfficiallySp/tftmixer#9]
Both the early and late Maestro tracks dominate the mix, and should have their volume lowered by 6-to-10 decibels.
Also, the Early Maestro tracks plays out of sync with the rest of the stems. Based on comparing it to the True Damage early set, I think it's playing about 2 seconds too late.

**Comment by OfficiallySp** [comment]
closing this as this is now completed
